name: Test RL implementations
on:
  push:
  pull_request:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Box2D build tools
        run: sudo apt-get update && sudo apt-get install -y swig
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r requirements.txt
      - name: Unit and integration tests
        run: python -m unittest discover -s tests -v
